### PR TITLE
Make RM_V empty by default

### PR DESCRIPTION
**Pull request by xexyl**
This is because in the past it rm was not used with -v.

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]
Does this need to be applied back to the mkiocccentry repo too, @xexyl ?

**Comment by xexyl** [comment]
> Does this need to be applied back to the mkiocccentry repo too, @xexyl ?

Do you mean should it be synced to the mkiocccentry repo or should it be done in the mkiocccentry repo? Or maybe both?

I guess the answer to both is it should be there but it probably is not critical?

**Comment by lcn2** [comment]
> Do you mean should it be synced to the mkiocccentry repo or should it be done in the mkiocccentry repo? Or maybe both?

Syncing with the mkiocccentry repo (from changes to the dbg repo, dyn_alloc repo, and critical changes to jparse) is a good thing to do for now (until we have a stable release).

**Comment by xexyl** [comment]
> > Do you mean should it be synced to the mkiocccentry repo or should it be done in the mkiocccentry repo? Or maybe both?
> 
> Syncing with the mkiocccentry repo (from changes to the dbg repo, dyn_alloc repo, and critical changes to jparse) is a good thing to do for now (until we have a stable release).

Agreed.

**Pull request merged**
