### PR TITLE
Update dbg facility documentation

### PR DESCRIPTION
**Pull request by xexyl**
The dbg.md file has been dramatically reduced in size, referring the
user to the man page instead. The man page has been updated with some
notes that were only in the md file and which is no longer there.

### CODE REVIEW

**Comment by xexyl** [comment]
If anything needs to be corrected I will be happy to do that either before or after a merge. I'll be trying to sleep again soon but hopefully this resolves the issue of dbg documentation being too long and too much.

**Comment by xexyl** [comment]
.. of course I actually meant README.md file here. That was a copy paste error.

**Comment by lcn2** [comment]
Thanks @xexyl , this will help the _dbg repo_ too once we get around to updating it.

**Comment by xexyl** [comment]
> Thanks @xexyl , this will help the _dbg repo_ too once we get around to updating it.

Happy to help my friend!

**Pull request merged**
